// src/app/components/poem-editor/poem-editor.component.ts
import { Component, signal, computed, inject } from '@angular/core';
import { SelectComponent } from '../select/select.component';
import { InputComponent } from '../input/input.component';
import { ButtonComponent } from '../button/button.component';
import { CardComponent } from '../card/card.component';
import { POETRY_FORMS, POETRY_FORM_OPTIONS, POETRY_EXAMPLES } from '../../data/poetry-forms.data';
import { RitaService } from '../../services/rita.service';
import { PoetryAnalyzerService } from '../../services/poetry-analyzer.service';

@Component({
  selector: 'app-poem-editor',
  standalone: true,
  imports: [SelectComponent, InputComponent, ButtonComponent, CardComponent],
  templateUrl: './poem-editor.component.html',
})
export class PoemEditorComponent {
  private readonly rita = inject(RitaService);
  readonly analyzer = inject(PoetryAnalyzerService);

  readonly formOptions = POETRY_FORM_OPTIONS;
  readonly selectedForm = signal('haiku');
  readonly poemText = signal('');

  readonly currentForm = computed(() => POETRY_FORMS[this.selectedForm()]);
  readonly lines = computed(() =>
    this.poemText()
      .split('\n')
      .filter((line) => line.trim().length > 0)
  );
  readonly lineCount = computed(() => this.lines().length);
  readonly totalSyllables = computed(() => {
    return this.lines().reduce((total, line) => {
      return total + this.rita.analyzeLine(line).syllables;
    }, 0);
  });

  onFormChange(formId: string): void {
    this.selectedForm.set(formId);
  }

  onTextChange(text: string): void {
    this.poemText.set(text);
  }

  loadExample(): void {
    const formId = this.selectedForm();
    const example = POETRY_EXAMPLES[formId];
    if (example) {
      this.poemText.set(example.join('\n'));
    }
  }

  clear(): void {
    this.poemText.set('');
    this.analyzer.clear();
  }

  analyze(): void {
    const formId = this.selectedForm();
    const lines = this.lines();

    if (lines.length === 0) return;

    this.analyzer.analyze(formId, lines);
  }
}

<!-- src/app/components/poem-editor/poem-editor.component.html -->
<app-card padding="large">
  <div class="space-y-6">
    <!-- Header -->
    <div>
      <h2 class="text-2xl font-light tracking-tight text-onSurface mb-2 lowercase">
        poetry analyzer
      </h2>
      <p class="text-sm text-onSurfaceVariant">
        write your poem and check if it matches the syllable pattern
      </p>
    </div>

    <!-- Form Selection -->
    <div>
      <app-select
        id="poetry-form"
        label="poetry form"
        [options]="formOptions"
        [value]="selectedForm()"
        (selectChange)="onFormChange($event)"
      />
      
      @if (currentForm(); as form) {
        <div class="mt-3 p-4 bg-primaryContainer text-onPrimaryContainer">
          <div class="flex items-center justify-between mb-2">
            <span class="text-sm font-semibold tracking-tight lowercase">
              pattern: {{ form.pattern.join('-') }} syllables
            </span>
            <span class="text-xs">
              {{ form.lines }} lines
            </span>
          </div>
          <p class="text-xs">
            {{ form.description }} · {{ form.origin }}
          </p>
        </div>
      }
    </div>

    <!-- Poem Input -->
    <div>
      <app-input
        id="poem-text"
        type="textarea"
        label="your poem"
        placeholder="write each line on a new line..."
        [rows]="8"
        [value]="poemText()"
        (inputChange)="onTextChange($event)"
      />
      
      <div class="flex items-center justify-between mt-2 text-xs text-onSurfaceVariant">
        <span>{{ lineCount() }} lines</span>
        <span>{{ totalSyllables() }} total syllables</span>
      </div>
    </div>

    <!-- Actions -->
    <div class="flex flex-wrap gap-3">
      <app-button
        variant="primary"
        size="medium"
        label="analyze poem"
        icon="icon-[iconoir--search]"
        [disabled]="lineCount() === 0"
        (clicked)="analyze()"
      />
      
      <app-button
        variant="secondary"
        size="medium"
        label="load example"
        icon="icon-[iconoir--page]"
        (clicked)="loadExample()"
      />
      
      <app-button
        variant="outline"
        size="medium"
        label="clear"
        icon="icon-[iconoir--cancel]"
        (clicked)="clear()"
      />
    </div>
  </div>
</app-card>

// src/lib/components/poetry/PoemEditor.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { POETRY_FORMS } from '$lib/data/poetry-forms.js';
	import {
		getFormName,
		getFormDescription,
		getFormExample,
		getCurrentLocale
	} from '$lib/services/i18n.js';

	export let lines: string = '';
	export let form: string = 'haiku';

	$: currentLines = lines.split('\n').filter((line) => line.trim());
	$: pattern = POETRY_FORMS[form]?.pattern || [];
	$: currentLocale = getCurrentLocale();

	const loadExample = () => {
		const example = getFormExample(form);
		if (example.length) lines = example.join('\n');
	};

	const clearText = () => (lines = '');
</script>

<div class="space-y-3">
	<!-- Form Selector -->
	<div>
		<label for="form-select" class="block text-sm font-medium text-onSurface mb-1">
			{m.poetry_form()}
		</label>
		<select
			id="form-select"
			class="w-full p-2 border border-outline rounded-md bg-surfaceContainer text-onSurface text-sm"
			bind:value={form}
		>
			{#each Object.keys(POETRY_FORMS) as formKey}
				<option value={formKey}>{getFormName(formKey)}</option>
			{/each}
		</select>
	</div>

	<!-- Pattern Info -->
	{#if pattern.length > 0}
		<div class="bg-primaryContainer p-3 rounded-md border border-outlineVariant">
			<h3 class="font-medium text-onPrimaryContainer">{getFormName(form)}</h3>
			<p class="text-sm text-onPrimaryContainer mb-1">
				Pattern: {pattern.join('-')} syllables
			</p>
			<p class="text-xs text-onPrimaryContainer/80">{getFormDescription(form)}</p>
		</div>
	{/if}

	<!-- Poem Input -->
	<div>
		<label for="poem-text" class="block text-sm font-medium text-onSurface mb-1">
			{m.your_poem()}
		</label>
		<textarea
			id="poem-text"
			class="w-full h-40 p-3 border border-outline rounded-md bg-surfaceContainer text-onSurface text-sm resize-none font-mono"
			bind:value={lines}
			placeholder={currentLocale === 'es'
				? 'Escribe cada verso en una línea nueva...'
				: 'Write each line on a new line...'}
		></textarea>
	</div>

	<!-- Action Buttons -->
	<div class="flex gap-2">
		<button type="button" class="btn-secondary text-xs" onclick={loadExample}>
			{m.load_example()}
		</button>
		<button type="button" class="btn-secondary text-xs" onclick={clearText}>
			{m.clear_text()}
		</button>
	</div>
</div>
